# Transpile both models to pure JavaScript via m2cgen, then dump a parity fixture so a Node script can confirm JS == Python
# To run this file so that you may generate modelA.js and modelB.js, type:  python scripts/export_models.py

import sys
import os
import json
import numpy as np
import pandas as pd
import joblib
import m2cgen as m2c

sys.setrecursionlimit(100000)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from src.features import engineer_features_a, patch_main
from src.config import MODEL_A_BASE_FEATURES, MODEL_B_BASE_FEATURES

MODEL_A_PATH = os.path.join(ROOT, "models", "modelA.pkl")
MODEL_B_PATH = os.path.join(ROOT, "models", "modelB.pkl")
WEB_MODELS = os.path.join(
    ROOT, "web", "static", "models"
)  # Preparing the path for models folder that will hold model_a.js and model_b.js
FIXTURE = os.path.join(ROOT, "scripts", "parity_fixture.json")

# The 20 engineered features from modelA.ipynb
MODEL_A_FULL_FEATURES = [
    "study_hours_per_day",
    "sleep_hours",
    "exam_pressure",
    "stress_level",
    "financial_stress",
    "social_support",
    "anxiety_score",
    "depression_score",
    "family_expectation",
    "physical_activity",
    "stress_x_anxiety",
    "stress_x_depression",
    "stress_x_exam",
    "anxiety_x_depression",
    "study_sleep_ratio",
    "pressure_support_gap",
    "stress_level_sq",
    "anxiety_score_sq",
    "sleep_deprived",
    "high_stress",
]


def write_esm(path, js_src, export_name):
    header = "// These numerous if-else are auto-generated by scripts/export_models.py via m2cgen. DO NOT EDIT.\n"
    js_src = js_src.replace(
        "function score(", f"function {export_name}("
    )  # Changing the default if-else function name, "score", into a more intuitive name: scoreModelA and scoreModelB
    with open(
        path, "w", encoding="utf-8"
    ) as f:  # Write to the file that is on that address
        f.write(
            header + js_src + f"\nexport {{ {export_name} }};\n"
        )  # Write the file with the given header: // These numerous..., the if-else function itself, and export { scoreModel... } so that the if-else function can be accessed


def main():
    os.makedirs(
        WEB_MODELS, exist_ok=True
    )  # Generate the output folder if the folder has not existed yet
    patch_main()

    # Load the trained models
    model_a = joblib.load(MODEL_A_PATH)
    model_b = joblib.load(MODEL_B_PATH)

    for m in (model_a, model_b):
        if m.get_params().get("num_parallel_tree") is None:
            m.set_params(
                num_parallel_tree=1
            )  # Number of tree generated per round is usually "None", we forced it to be set to be 1
            # Getting the base_score so that the transpilation process by mc2gen can translate hundreds or even thousands of XGBoost decision tree into an enormous if-else function
        if m.get_params().get("base_score") is None:
            cfg = json.loads(m.get_booster().save_config())
            raw = cfg["learner"]["learner_model_param"]["base_score"]  # Diving deeper
            vals = [float(v) for v in raw.strip("[]").split(",")]
            assert len(set(vals)) == 1, f"non-uniform base_score: {vals}"
            base = vals[0]
            m.set_params(base_score=base)  # Get ONE base_score

    js_a = m2c.export_to_javascript(model_a, function_name="score")
    write_esm(
        os.path.join(WEB_MODELS, "model_a.js"), js_a, "scoreModelA"
    )  # Writing the file model_a.js with the given path

    js_b = m2c.export_to_javascript(model_b, function_name="score")
    write_esm(
        os.path.join(WEB_MODELS, "model_b.js"), js_b, "scoreModelB"
    )  # Writing the file model_b.js with the given path

    # Generate a benchmark data (or cheatsheet) so that we can compare the result predicted/generated by Python models and the result that is generated by JS models
    rng = np.random.default_rng(7)
    N = 500
    rows = pd.DataFrame(
        {
            "study_hours_per_day": rng.uniform(0, 12, N),
            "sleep_hours": rng.uniform(3, 11, N),
            "exam_pressure": rng.uniform(0, 10, N),
            "stress_level": rng.uniform(0, 10, N),
            "financial_stress": rng.uniform(0, 10, N),
            "social_support": rng.uniform(0, 10, N),
            "anxiety_score": rng.uniform(0, 10, N),
            "depression_score": rng.uniform(0, 10, N),
            "family_expectation": rng.uniform(0, 10, N),
            "physical_activity": rng.uniform(0, 13, N),
        }
    )

    eng = engineer_features_a(rows)[MODEL_A_FULL_FEATURES]
    proba_a = model_a.predict_proba(eng.values)  # Creating a "cheatsheet" for model A

    b_in = pd.DataFrame(
        {
            "study_hours": rng.uniform(5, 10, N),
            "eca_hours": rng.uniform(0, 4, N),
            "sleep_hours": rng.uniform(5, 10, N),
            "social_hours": rng.uniform(0, 6, N),
            "physical_hours": rng.uniform(0, 13, N),
            "stress_level": rng.integers(0, 3, N).astype(float),
        }
    )[MODEL_B_BASE_FEATURES]
    gpa_b = model_b.predict(b_in.values)  # Creating a "cheatsheet" for model B

    fixture = {
        "model_a": {
            "feature_order": MODEL_A_FULL_FEATURES,
            "inputs": eng.values.tolist(),
            "expected_proba": proba_a.tolist(),
        },
        "model_b": {
            "feature_order": MODEL_B_BASE_FEATURES,
            "inputs": b_in.values.tolist(),
            "expected_gpa": gpa_b.tolist(),
        },
    }
    with open(FIXTURE, "w", encoding="utf-8") as f:
        json.dump(
            fixture, f
        )  # Writing the fixture or the cheatsheet to be use as a comparison tool


if __name__ == "__main__":
    main()