"""Transpile both models to pure JavaScript via m2cgen, then dump a parity
fixture so a Node script can confirm JS == Python.

Model A : modelA.pkl  (XGBClassifier, multi:softprob)
          m2cgen emits score(input) -> [raw_0, raw_1, raw_2] (logits).
          The browser applies softmax to recover probabilities.
Model B : modelB.pkl  (XGBRegressor)
          m2cgen emits score(input) -> gpa (single float).

Outputs:
    web/static/models/model_a.js        (ESM, exports scoreModelA)
    web/static/models/model_b.js        (ESM, exports scoreModelB)
    scripts/parity_fixture.json  (inputs + expected Python outputs)

Run from repo root:  python scripts/export_models.py
"""

import sys
import os
import json
import numpy as np
import pandas as pd
import joblib
import warnings

warnings.filterwarnings("ignore")
import m2cgen as m2c

# m2cgen builds a deeply-nested AST (one frame per tree); large ensembles
# exceed CPython's default 1000-frame recursion limit during assembly.
sys.setrecursionlimit(100000)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from src.features import engineer_features_a, patch_main
from src.config import MODEL_A_BASE_FEATURES, MODEL_B_BASE_FEATURES

MODEL_A_PATH = os.path.join(ROOT, "models", "modelA.pkl")
MODEL_B_PATH = os.path.join(ROOT, "models", "modelB.pkl")
WEB_MODELS = os.path.join(ROOT, "web", "static", "models")
FIXTURE = os.path.join(ROOT, "scripts", "parity_fixture.json")

# Feature order Model A expects AFTER engineering (matches notebooks/modelA.ipynb)
MODEL_A_FULL_FEATURES = [
    "study_hours_per_day", "sleep_hours", "exam_pressure", "stress_level",
    "financial_stress", "social_support", "anxiety_score", "depression_score",
    "family_expectation", "physical_activity",
    "stress_x_anxiety", "stress_x_depression", "stress_x_exam",
    "anxiety_x_depression", "study_sleep_ratio", "pressure_support_gap",
    "stress_level_sq", "anxiety_score_sq", "sleep_deprived", "high_stress",
]


def write_esm(path, js_src, export_name):
    header = (
        "// AUTO-GENERATED by scripts/export_models.py via m2cgen. DO NOT EDIT.\n"
    )
    js_src = js_src.replace("function score(", f"function {export_name}(")
    with open(path, "w", encoding="utf-8") as f:
        f.write(header + js_src + f"\nexport {{ {export_name} }};\n")


def main():
    os.makedirs(WEB_MODELS, exist_ok=True)
    patch_main()

    print("Loading models ...")
    model_a = joblib.load(MODEL_A_PATH)
    model_b = joblib.load(MODEL_B_PATH)

    # xgboost 3.x leaves num_parallel_tree=None in get_params(); m2cgen's
    # multiclass splitter does `n_classes * params_seq_len` and crashes on None.
    # Force the boosting default (1) so transpilation succeeds. Pure metadata —
    # does not touch the trained booster.
    for m in (model_a, model_b):
        if m.get_params().get("num_parallel_tree") is None:
            m.set_params(num_parallel_tree=1)
        # xgboost 3.x learns base_score into the booster but leaves
        # get_params()["base_score"] = None; m2cgen then emits a `nan`
        # intercept. Pull the real value out of the booster config and inject
        # it so the transpiled JS matches predict()/predict_proba() exactly.
        if m.get_params().get("base_score") is None:
            cfg = json.loads(m.get_booster().save_config())
            raw = cfg["learner"]["learner_model_param"]["base_score"]
            # raw is either a scalar string ("3.0E0") or a per-class vector
            # ("[0E0,0E0,0E0]"). m2cgen wants a single scalar applied to every
            # class output, which is valid here because the vector is uniform.
            vals = [float(v) for v in raw.strip("[]").split(",")]
            assert len(set(vals)) == 1, f"non-uniform base_score: {vals}"
            base = vals[0]
            m.set_params(base_score=base)
            print(f"  injected base_score={base}")

    print("Transpiling Model A -> JS ...")
    js_a = m2c.export_to_javascript(model_a, function_name="score")
    write_esm(os.path.join(WEB_MODELS, "model_a.js"), js_a, "scoreModelA")

    print("Transpiling Model B -> JS ...")
    js_b = m2c.export_to_javascript(model_b, function_name="score")
    write_esm(os.path.join(WEB_MODELS, "model_b.js"), js_b, "scoreModelB")

    for n in ("model_a.js", "model_b.js"):
        kb = os.path.getsize(os.path.join(WEB_MODELS, n)) / 1024
        print(f"  web/static/models/{n}: {kb:.1f} KB")

    # ----- build parity fixture from random plausible rows -----
    print("Building parity fixture ...")
    rng = np.random.default_rng(7)
    N = 500
    rows = pd.DataFrame({
        "study_hours_per_day": rng.uniform(0, 12, N),
        "sleep_hours":         rng.uniform(3, 11, N),
        "exam_pressure":       rng.uniform(0, 10, N),
        "stress_level":        rng.uniform(0, 10, N),
        "financial_stress":    rng.uniform(0, 10, N),
        "social_support":      rng.uniform(0, 10, N),
        "anxiety_score":       rng.uniform(0, 10, N),
        "depression_score":    rng.uniform(0, 10, N),
        "family_expectation":  rng.uniform(0, 10, N),
        "physical_activity":   rng.uniform(0, 13, N),
    })

    eng = engineer_features_a(rows)[MODEL_A_FULL_FEATURES]
    proba_a = model_a.predict_proba(eng.values)  # softmax(logits) reference

    # Model B uses 6 raw features in a fixed order
    b_in = pd.DataFrame({
        "study_hours":    rng.uniform(5, 10, N),
        "eca_hours":      rng.uniform(0, 4, N),
        "sleep_hours":    rng.uniform(5, 10, N),
        "social_hours":   rng.uniform(0, 6, N),
        "physical_hours": rng.uniform(0, 13, N),
        "stress_level":   rng.integers(0, 3, N).astype(float),
    })[MODEL_B_BASE_FEATURES]
    gpa_b = model_b.predict(b_in.values)

    fixture = {
        "model_a": {
            "feature_order": MODEL_A_FULL_FEATURES,
            "inputs": eng.values.tolist(),
            "expected_proba": proba_a.tolist(),
        },
        "model_b": {
            "feature_order": MODEL_B_BASE_FEATURES,
            "inputs": b_in.values.tolist(),
            "expected_gpa": gpa_b.tolist(),
        },
    }
    with open(FIXTURE, "w", encoding="utf-8") as f:
        json.dump(fixture, f)
    print(f"Wrote {FIXTURE} ({N} rows)")
    print("Done.")


if __name__ == "__main__":
    main()
